name: run program

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "23 2 * * *" # 4:23am every day israel time (1:23 UTC time)

permissions: write-all

jobs:
  run:
    runs-on: ubuntu-latest

    services:
      proxy-vpn:
        image: ghcr.io/tal-sitton/proxy-vpn:latest
        ports:
          - 8118:8118
        env:
          PASTE_DEV_KEY: ${{ secrets.PASTE_DEV_KEY }}
          PASTE_USER_KEY: ${{ secrets.PASTE_USER_KEY }}
          PASTE_KEYS: ${{ secrets.PASTE_KEYS }}
        options: >-
          --name proxy
          --privileged

    steps:
      - uses: actions/checkout@v4
        if: github.event_name == 'pull_request'
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/checkout@v4
        if: github.event_name != 'pull_request'
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      - name: run update
        run: |
            chmod +x ./update.sh
            ./update.sh

      - name: config git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: add maps_hvr_files
        run:
          git add maps_hvr_files/*

      - name: commit file and push
        run: |
          git commit -m "Update businesses"
          git push